// Type pour les métadonnées de la page, utilisé par Next.js pour le SEO
import type { Metadata } from "next";

// Importation de la police "Inter" via Next.js (optimisé)
import { Inter } from "next/font/google";

import "./globals.css";

// Adapter Nuqs pour synchroniser l'état avec l'URL dans App Router
import { NuqsAdapter } from "nuqs/adapters/next/app";

// Fournisseur d'authentification côté serveur avec Convex + Next.js
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

// Fournisseur du client Convex (permet d'utiliser useQuery, useMutation, etc.)
import { ConvexClientProvider } from "@/components/convex-client-provider";

// Composants de modales globales (affichables depuis n'importe où)
import { Modals } from "@/components/modals";

// Composant pour afficher les notifications (type toaster/snackbar)
import { Toaster } from "@/components/ui/sonner";
// Fournisseur d’état global basé sur Jotai
import { JotaiProvider } from "@/components/joati-provider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout racine de l'application, englobant tous les composants
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Fournisseur d’authentification Convex côté serveur
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* Adapter Nuqs pour gérer les paramètres d’URL (ex : filtres, pagination) */}
          <NuqsAdapter>
            {/* Fournisseur client Convex pour les requêtes en temps réel */}
            <ConvexClientProvider>
              <JotaiProvider>
                {/* Composant global de notifications (toasts) */}
                <Toaster />
                {/* Composants de modales, visibles de n'importe où dans l'app */}
                <Modals />
                {/* Contenu de chaque page */}
                {children}
              </JotaiProvider>
            </ConvexClientProvider>
          </NuqsAdapter>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
